### ISSUE TITLE
bug in CDA with locales and richtext field

### ISSUE THREAD

**Issue by denisyilmaz** [contentful/rich-text#59]
Hi, i don't know if this is the right repo but as its connected to richtext I guessed its a good starting point. If I should submit it in another repo, please let me know.

If using RichText fields with multiple locales, the response of a locale with missing content for a RichText field doesn't fallback to the default locale.

### Language Content: 

EN : __'some Englisch content'__
DE: __undefined__

DE is set to fallback to EN.

### currently: 

```json
{
"sys": { "lang": "en"},
"fields": {
 "richtext": "some English content"
}
```

```json
{
"sys": {"lang": "de"},
"fields": {
 "richtext": ""
}
```

### expected:

```json
{
"sys": { "lang": "de"},
"fields": {
  "richtext": "some English content"
}
```

all other fields are showing correct fallback content, but all RichText fields don't.

**Comment by sbezludny** [comment]
Thanks for the reporting. 
I will create a ticket in our internal bug tracker and reach out to you when I have any updates.

**Comment by cribbles** [comment]
Hi Denis! I'm one of the engineers working on this feature.

The bug you mention is due to a quirk in the way we implemented the rich text editor in our web-app, having to do with the way empty documents were passed from the client-side to the server side. We've since addressed the issue in a patch that shipped this morning.

Importantly, the patch doesn't _backfill_ existing empty locale fields. (The bug is fixed for any locale fields created in the future, though.) As a workaround for existing locale fields where this is a problem, simply add some content to the locale fields you want to be empty (i.e. to fall back to the default locale), immediately remove the content (i.e., make the editor state empty completely again), then republish the entry. The affected field(s) should now fall back to the default locale.

Since this bug is unrelated to the repo at hand, I'm going to go ahead and close this issue with this comment. However, please let us know if you continue to have any problems with this behavior. Thanks again for bringing this to our attention!

**Comment by cribbles** [comment]
Glad to hear that!

In this case, it was an internal repo. In the future, you're welcome to file a [support ticket](https://www.contentful.com/support/) for this kind of thing :)
