### ISSUE TITLE
Hyperlink target property is being appended to data uri link

### ISSUE THREAD

**Issue by mouthzipper** [contentful/rich-text#87]
![image](https://user-images.githubusercontent.com/5491562/56152648-dad4b280-5fe6-11e9-9e52-23c88b65c106.png)

See above screeshot the details. I'm using rich-text-html-renderer

**Comment by sbezludny** [comment]
Hey @mouthzipper,

let me check if I understood you correctly:
after setting `<a href="https://example.com" target="_blank">`, as a link target in the web app you're receiving `"https://example.com" target=\"_blank\""` from the API?

**Comment by mouthzipper** [comment]
@sbezludny I'm receiving `"https://example.com target="_blank""` as the data `uri` value. I get around with it temporarily by splitting the values and manually constructing the `a` tag values

**Comment by sbezludny** [comment]
On the attached screenshot I see that it's set to `<a href="..." target="_blank">` this will result in an incorrect output from `rich-text-html-renderer` because the renderer will put this value as an `href` attribute of the html anchor element.

Although the web app allows setting an arbitrary string as Link Target of the Hyperlink, we recommend to set it to a URI, for your case

```
Link target: https://example.org
```
